### ISSUE TITLE
rendered post output is breaking layout

### ISSUE THREAD

**Issue by kristoferjoseph** [beginner-corp/blog.begin.com#30]
https://sing-xe3-staging.begin.app/posts/2020-03-30-transpiling-javascript-with-babel-on-begin.md

Something in this post is breaking the layout.

**Comment by macdonst** [comment]
What's broken? I checked it in 3 different browsers.

**Comment by kristoferjoseph** [comment]
On mobile it scrolls horizontally.
![Screenshot_20211001-075536](https://user-images.githubusercontent.com/76308/135641698-896b7ebf-583a-4cba-87b4-e826d096f956.png)

**Comment by ryanblock** [comment]
Issue replicates for me on iPhone 12.

**Comment by macdonst** [comment]
Oh, mobile testing. Yes, I can reproduce too on any resolution less than 430px wide but it's not just that post it's all posts for me.

**Comment by tbeseda** [comment]
I get the issue on mobile on _some_ but not all posts.
like 
https://sing-xe3-staging.begin.app/posts/2020-07-15-how-to-rename-your-master-branch-to-main-or-something-else.md
https://sing-xe3-staging.begin.app/posts/2020-12-21-architect-8-4-say-hello-to-lambda-treeshaking.md

but not 
https://sing-xe3-staging.begin.app/posts/2020-12-09-architect-8-3-custom-file-paths-much-more.md
